# Define the server block
server {
    listen 5000;  # Listen on port 80

    # Root directory for serving the Angular app
    #root /usr/share/nginx/html;

    
    
    location /agent-desktop {
        root /usr/share/nginx/html;
        index /agent-destop/index.html;
    }

    # Handle 404 errors by redirecting to the root path
    error_page 404 /agent-desktop/index.html;
}
