# Define the server block
server {
    listen 13032;  # Listen on port 80

    # Root directory for serving the Angular app
    #root /usr/share/nginx/html;

    
    
    location /agent-desktop {
        root /tetherfi/tetherfihome;
        index /agent-destop/index.html;
    }

    # Handle 404 errors by redirecting to the root path
    error_page 404 /agent-desktop/index.html;
}
